tap "caskroom/cask"
tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/services"
tap "homebrew/versions"
tap "tldr-pages/tldr"

brew "hub"
brew "postgresql", restart_service: true
brew "sqlite"
brew "python3"
brew "haskell-stack"
brew "rbenv"
brew "redis", restart_service: true
brew "tldr"
brew "tree"
brew "wifi-password"
brew "yarn", args: ["without-node"]
brew "z"
brew "zsh"
brew "zsh-completions"

cask "slack"
cask "atom"
cask "dropbox"
cask "sourcetree"
cask "github"
cask "sip"
cask "1password"
cask "moom"
cask "dash"
cask "alfred"
cask "qlimagesize"

cask "font-source-code-pro-for-powerline"
cask "flux"
